// <auto-generated />
using System;
using CapTestAutomationDemo.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CapTestAutomationDemo.Migrations
{
    [DbContext(typeof(CapTestAutomationDemoContext))]
    [Migration("20190326092550_EngineSize")]
    partial class EngineSize
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.3-rtm-32065")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CapTestAutomationDemo.Models.VehiclesModel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BodyStyle");

                    b.Property<string>("CarModel");

                    b.Property<double>("EngineSize");

                    b.Property<string>("FuelType");

                    b.Property<int>("InsurancePackage");

                    b.Property<string>("Make");

                    b.Property<DateTime>("Year");

                    b.HasKey("ID");

                    b.ToTable("VehiclesModel");
                });
#pragma warning restore 612, 618
        }
    }
}
